# Generated by Django 5.0.6 on 2024-06-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
            ],
        ),
    ]
